### ISSUE TITLE
Enable toggle cockpit

### ISSUE THREAD

**Issue by dsatgh** [sryu1/DA40#3]
I would like to see toggle the cockpit with 'c' key enabled as it's kind of a standard in FG aircraft. The autopilot CWS should therefore be reassigned from 'c' to the FG standard 'd' key.

```
/da40ng-base.xml
                <aero archive="y">da40ng-jsb</aero>
+               <allow-toggle-cockpit type="bool">true</allow-toggle-cockpit>
                
/da40ng-jsb-club-set.xml
                        <!-- CWS begin -->
-                       <key n="99">
-                               <name>c</name>
+                       <key n="100">
+                               <name>d</name>
```
EDIT: I've seen that the G1000 variant seems to be using the 'c' key as well. Not nice ;)

**Comment by sryu1** [comment]
Thank you. The "c" key also works with G1000 without any changes to its own file.

**Comment by sryu1** [comment]
Also, feel free to open pull requests then I can merge it quickly :)

**Comment by dsatgh** [comment]
Thanks for the change. I will look into pull requests the next time :)
